language: julia
os:
  - osx
  - linux
julia:
  - 0.6
#  - 0.5
  - nightly
matrix:
  allow_failures:
    julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SubClonalSelection"); Pkg.test("SubClonalSelection"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("SubClonalSelection")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("SubClonalSelection")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
